language: node_js
node_js:
  - '0.10'
env:
  global:
  - secure: BBjPnhHTvOzkstt63xTVNvGxcCKkMUWhHs23Be5M9ZUr+nydWPGONzjH67x9QRskAkL6EJDzR5EiqRWuUeYWv9K1lDL7lrCbZIenwnE/Pij9Jc+p7gytk8wZRhpT7tEL+ZsfiWTzNQcqMkU83WS0VUJOLG7O03L/o1jNmMj+rm4=
  - secure: dyO6/4bz3VQWz3T2gFxOhxL0pRFvylEtUBIMoj5MQwnBRaR+OWFa/+KylwfSz8CJED6XFausNMjUmIF5jLJos+JBDk+lepNXfRIodPHrj0MnNQV/hVWmSIz1S7+aAEQuDxuvaTiA3qaq6RTCvlafIS3/aYWf5kYr6Ik1vLeAJ7w=
addons:
  sauce_connect: true
