language: node_js
node_js:
- '0.10'
env:
  global:
    secure: dP+x1gwyzQ/8VN5d9OSUV1K0dI0Co1RgaTPq3ufpey5EQHFO/wS1rR1UNcjsMmVHiZwZHLxcJyZFxO6BavO05HJyLFBcmgjmA5G1zqQsWFtelNEnS4l/1628jKkKSUanhKMHMmSH9g94RwJU+yKqcHra2yHMZCgSTQAwGzRz9q8=
