language: node_js
node_js:
  - '0.10'
env:
  global:
    secure: "YPrvtISzDKSh1Yaj/jvyG0l9t2Djq6I3UQRjoWvGtWND0S2uyVqV8mtyoqbk0TWHTu3HaVplTaEIt9V+2E+UAN06dRILekNPlL1Ib4PnIDrE3s2KXUYkZa00hv6XtTYbpwOpm2c8it7k5r0fC2kyjJG3y+Z7UHcWufpfXqtDWqg="
